sudo: false
language: ruby
cache: bundler
dist: precise

services:
  - mysql
  - postgresql

before_install:
  - gem install bundler

before_script:
  - mysql -e 'create database makara_test;'
  - psql -c 'create database makara_test;' -U postgres
  - psql -c 'create extension postgis;' -U postgres

rvm:
  - 2.6
  - 2.7
  - ruby-head

gemfile:
  - gemfiles/ar52.gemfile
  - gemfiles/ar60.gemfile
  - gemfiles/ar-head.gemfile

matrix:
  allow_failures:
    - gemfile: gemfiles/ar-head.gemfile
    - gemfile: gemfiles/ar60.gemfile
    - rvm: ruby-head
  fast_finish: true
